name: Build and Create Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build wheel
      run: |
        python setup.py bdist_wheel
    - name: Test with pytest
      run: |
        pytest
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
          files: |
            dist/anime_manager-1.0-py3-none-any.whl
